RKDG2D: Cell Class Reference
Cell Class Reference
#include <Cell.h>
Public Member Functions
Cell (const Problem &prb)
Constructor.
Cell (const std::vector< std::shared_ptr< Node > > &nodes, const std::vector< std::shared_ptr< Edge > > &edges, const Problem &prb)
Construct cell using vectors of nodes and edges.
~Cell ()
Destructor.
double getArea () const
Return area of cell.
const Point & getCellCenter () const
Return center of cell.
void setArea ()
Calculate element area.
void setCellCenter ()
Set cell center.
void setJacobian ()
Define Jacobian function.
void setGaussPoints ()
Set Gauss points.
void setBasisFunctions ()
Set basis functions.
std::vector< std::shared_ptr< Point > > getCellCoordinates () const
Calculate coordinates of cell nodes.
void findNeighbourCells ()
Find neighbour cells.
std::vector< std::shared_ptr< Cell > > findNeighbourCellsX () const
Find neighbour cells in X direction.
std::vector< std::shared_ptr< Cell > > findNeighbourCellsY () const
Find neighbour cells in Y direction.
bool insideCell (const Point &point) const
Check if point belongs cell.
numvector< double, 5 > reconstructSolution (const Point &point) const
Reconstruct solution in defined point (get coeffs from problem)
double reconstructSolution (const Point &point, int numSol) const
numvector< double, 5 > reconstructSolution (const std::shared_ptr< Point > point) const
double reconstructSolution (const std::shared_ptr< Point > point, int numSol) const
numvector< double, 5 > reconstructSolution (const Point &point, const numvector< double, 5 *nShapes > &alpha) const
Reconstruct solution using given coeffs.
double reconstructSolution (const Point &point, const numvector< double, 5 *nShapes > &alpha, int numSol) const
numvector< double, 5 > reconstructSolution (const std::shared_ptr< Point > point, const numvector< double, 5 *nShapes > &alpha) const
double reconstructSolution (const std::shared_ptr< Point > point, const numvector< double, 5 *nShapes > &alpha, int numSol) const
numvector< double, 5 *nShapes > reconstructCoefficients (const std::pair< numvector< double, 5 *nShapes >, numvector< double, 5 *nShapes >> &rI) const
Reconstruct coefficients using Riemann invariants.
numvector< double, 5 *nShapes > reconstructCoefficients (const numvector< double, 5 *nShapes > &rI, const Point &n) const
numvector< double, 5 *nShapes > reconstructCoefficients (const numvector< double, 5 *nShapes > &rI, const Point &n, const numvector< numvector< double, 5 >, 5 > &L) const
numvector< double, 5 *nShapes > projection (std::function< numvector< double, 5 >(const Point &point)> &init) const
Get coefficients of projection of function foo onto cell basis.
std::pair< numvector< double, 5 *nShapes >, numvector< double, 5 *nShapes > > getRiemannInvariants ()
Get Riemann invariants using actual solution on cell.
numvector< double, 5 *nShapes > getRiemannInvariants (const Point &n)
numvector< double, 5 *nShapes > getRiemannInvariants (const Point &n, const numvector< numvector< double, 5 >, 5 > &R)
void setGramian ()
Calculate Gramian matrix.
numvector< double, 5 *nShapes > correctNonOrtho (const numvector< double, 5 *nShapes > &rhs) const
Solve SLAE in case of non-orthogonal functions.
numvector< double, 5 *nShapes > correctPrevIter (const numvector< double, 5 *nShapes > &rhs) const
Reconstruct SLAE RHS after limitation in case of non-orthogonal functions.
numvector< double, 5 *nShapes > cellIntegral ()
Calculate {cell} F(U) + G(U) .
double totalMassFlux () const
Calculate total mass flux.
double totalMass () const
Calculate total mass in cell.
double integrate (const std::function< double(const Point &)> &f) const
2D Gauss integration of scalar function
numvector< double, 5 > integrate (const std::function< numvector< double, 5 >(const Point &)> &f) const
2D Gauss integration of vector function
double getNormQ (int numSol) const
Get norm of solution for indicators.
double getNormQp () const
Get norm of pressure for indicators.
Public Attributes
int number
Number of cell.
int nEntities
Number of entities (edges or nodes - mo matter, they're similar)
std::vector< std::shared_ptr< Node > > nodes
Nodes in cell.
std::vector< std::shared_ptr< Edge > > edges
Edges in cell.
std::vector< std::shared_ptr< Cell > > neibCells
Neighbour cells.
const Problem & problem
Const reference to problem.
std::vector< std::function< double(const Point &)> > phi
List of basis functions.
std::vector< double > offsetPhi
Offset for basis functions.
std::vector< std::function< Point(const Point &)> > gradPhi
Gradient of basis functions.
Private Member Functions
Point localToGlobal (const Point &localPoint) const
local [-1,1]x[-1,1] to global rectangular cell
Private Attributes
int nGP
Number of Gauss points.
std::vector< Point > gPoints2D
Gauss points.
std::vector< double > gWeights2D
Gauss weights.
std::vector< double > J
Jacobian.
double area
Area of cell.
Point center
Mass center of cell.
std::vector< std::vector< double > > gramian
Gramian matrix.
Detailed Description
Definition at line 21 of file Cell.h.
Constructor & Destructor Documentation
Cell() [1/2]
Cell::Cell (const Problem & prb) inline
Constructor.
Definition at line 88 of file Cell.h.
Cell() [2/2]
Cell::Cell (const std::vector< std::shared_ptr< Node > > & nodes, const std::vector< std::shared_ptr< Edge > > & edges, const Problem & prb)
Construct cell using vectors of nodes and edges.
~Cell()
Cell::~Cell () inline
Destructor.
Definition at line 94 of file Cell.h.
Member Function Documentation
cellIntegral()
numvector<double, 5 * nShapes> Cell::cellIntegral ()
Calculate {cell} F(U) + G(U) .
correctNonOrtho()
numvector<double, 5 * nShapes> Cell::correctNonOrtho (const numvector< double, 5 *nShapes > & rhs) const
Solve SLAE in case of non-orthogonal functions.
correctPrevIter()
numvector<double, 5 * nShapes> Cell::correctPrevIter (const numvector< double, 5 *nShapes > & rhs) const
Reconstruct SLAE RHS after limitation in case of non-orthogonal functions.
findNeighbourCells()
void Cell::findNeighbourCells ()
Find neighbour cells.
findNeighbourCellsX()
std::vector<std::shared_ptr<Cell> > Cell::findNeighbourCellsX () const
Find neighbour cells in X direction.
findNeighbourCellsY()
std::vector<std::shared_ptr<Cell> > Cell::findNeighbourCellsY () const
Find neighbour cells in Y direction.
getArea()
double Cell::getArea () const inline
Return area of cell.
Definition at line 99 of file Cell.h.
References area.
getCellCenter()
const Point& Cell::getCellCenter () const inline
Return center of cell.
Definition at line 102 of file Cell.h.
References center.
getCellCoordinates()
std::vector<std::shared_ptr<Point> > Cell::getCellCoordinates () const
Calculate coordinates of cell nodes.
getNormQ()
double Cell::getNormQ (int numSol) const
Get norm of solution for indicators.
getNormQp()
double Cell::getNormQp () const
Get norm of pressure for indicators.
getRiemannInvariants() [1/3]
std::pair<numvector<double, 5 * nShapes>, numvector<double, 5 * nShapes> > Cell::getRiemannInvariants ()
Get Riemann invariants using actual solution on cell.
getRiemannInvariants() [2/3]
numvector<double, 5 * nShapes> Cell::getRiemannInvariants (const Point & n)
getRiemannInvariants() [3/3]
numvector<double, 5 * nShapes> Cell::getRiemannInvariants (const Point & n, const numvector< numvector< double, 5 >, 5 > & R)
insideCell()
bool Cell::insideCell (const Point & point) const
Check if point belongs cell.
integrate() [1/2]
double Cell::integrate (const std::function< double(const Point &)> & f) const
2D Gauss integration of scalar function
integrate() [2/2]
numvector<double,5> Cell::integrate (const std::function< numvector< double, 5 >(const Point &)> & f) const
2D Gauss integration of vector function
localToGlobal()
Point Cell::localToGlobal (const Point & localPoint) const private
local [-1,1]x[-1,1] to global rectangular cell
projection()
numvector<double, 5 * nShapes> Cell::projection (std::function< numvector< double, 5 >(const Point &point)> & init) const
Get coefficients of projection of function foo onto cell basis.
reconstructCoefficients() [1/3]
numvector<double, 5 * nShapes> Cell::reconstructCoefficients (const std::pair< numvector< double, 5 *nShapes >, numvector< double, 5 *nShapes >> & rI) const
Reconstruct coefficients using Riemann invariants.
reconstructCoefficients() [2/3]
numvector<double, 5 * nShapes> Cell::reconstructCoefficients (const numvector< double, 5 *nShapes > & rI, const Point & n) const
reconstructCoefficients() [3/3]
numvector<double, 5 * nShapes> Cell::reconstructCoefficients (const numvector< double, 5 *nShapes > & rI, const Point & n, const numvector< numvector< double, 5 >, 5 > & L) const
reconstructSolution() [1/8]
numvector<double, 5> Cell::reconstructSolution (const Point & point) const
Reconstruct solution in defined point (get coeffs from problem)
Referenced by reconstructSolution().
reconstructSolution() [2/8]
double Cell::reconstructSolution (const Point & point, int numSol) const
reconstructSolution() [3/8]
numvector<double, 5> Cell::reconstructSolution (const std::shared_ptr< Point > point) const inline
Definition at line 144 of file Cell.h.
References reconstructSolution().
reconstructSolution() [4/8]
double Cell::reconstructSolution (const std::shared_ptr< Point > point, int numSol) const inline
Definition at line 146 of file Cell.h.
References reconstructSolution().
reconstructSolution() [5/8]
numvector<double, 5> Cell::reconstructSolution (const Point & point, const numvector< double, 5 *nShapes > & alpha) const
Reconstruct solution using given coeffs.
reconstructSolution() [6/8]
double Cell::reconstructSolution (const Point & point, const numvector< double, 5 *nShapes > & alpha, int numSol) const
reconstructSolution() [7/8]
numvector<double, 5> Cell::reconstructSolution (const std::shared_ptr< Point > point, const numvector< double, 5 *nShapes > & alpha) const inline
Definition at line 153 of file Cell.h.
References reconstructSolution().
reconstructSolution() [8/8]
double Cell::reconstructSolution (const std::shared_ptr< Point > point, const numvector< double, 5 *nShapes > & alpha, int numSol) const inline
Definition at line 155 of file Cell.h.
References reconstructSolution().
setArea()
void Cell::setArea ()
Calculate element area.
setBasisFunctions()
void Cell::setBasisFunctions ()
Set basis functions.
setCellCenter()
void Cell::setCellCenter ()
Set cell center.
setGaussPoints()
void Cell::setGaussPoints ()
Set Gauss points.
setGramian()
void Cell::setGramian ()
Calculate Gramian matrix.
setJacobian()
void Cell::setJacobian ()
Define Jacobian function.
totalMass()
double Cell::totalMass () const
Calculate total mass in cell.
totalMassFlux()
double Cell::totalMassFlux () const
Calculate total mass flux.
Member Data Documentation
area
double Cell::area private
Area of cell.
Definition at line 39 of file Cell.h.
Referenced by getArea().
center
Point Cell::center private
Mass center of cell.
Definition at line 42 of file Cell.h.
Referenced by getCellCenter().
edges
std::vector<std::shared_ptr<Edge> > Cell::edges
Edges in cell.
Definition at line 65 of file Cell.h.
gPoints2D
std::vector<Point> Cell::gPoints2D private
Gauss points.
Definition at line 30 of file Cell.h.
gradPhi
std::vector<std::function<Point(const Point&)> > Cell::gradPhi
Gradient of basis functions.
Definition at line 83 of file Cell.h.
gramian
std::vector<std::vector<double> > Cell::gramian private
Gramian matrix.
Definition at line 45 of file Cell.h.
gWeights2D
std::vector<double> Cell::gWeights2D private
Gauss weights.
Definition at line 33 of file Cell.h.
J
std::vector<double> Cell::J private
Jacobian.
Definition at line 36 of file Cell.h.
neibCells
std::vector<std::shared_ptr<Cell> > Cell::neibCells
Neighbour cells.
Definition at line 68 of file Cell.h.
nEntities
int Cell::nEntities
Number of entities (edges or nodes - mo matter, they're similar)
Definition at line 59 of file Cell.h.
nGP
int Cell::nGP private
Number of Gauss points.
Definition at line 27 of file Cell.h.
nodes
std::vector<std::shared_ptr<Node> > Cell::nodes
Nodes in cell.
Definition at line 62 of file Cell.h.
number
int Cell::number
Number of cell.
Definition at line 56 of file Cell.h.
offsetPhi
std::vector<double> Cell::offsetPhi
Offset for basis functions.
Definition at line 80 of file Cell.h.
phi
std::vector<std::function<double(const Point&)> > Cell::phi
List of basis functions.
Definition at line 76 of file Cell.h.
problem
const Problem& Cell::problem
Const reference to problem.
Definition at line 73 of file Cell.h.
The documentation for this class was generated from the following file:
Cell.h